### ISSUE TITLE
fork's on_start

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_terminal#12]
@Jairo-Martinez
you added on_start in install.inf. to show sidebar button on start? better do this w/o using on_start. see how plugin cuda_snippet_panel does it via install.inf.

**Comment by Alexey-T** [comment]
https://wiki.freepascal.org/CudaText#Format_of_install.inf_files

**Comment by Alexey-T** [comment]
wiki tells about it:
https://wiki.freepascal.org/CudaText#Format_of_install.inf_files

**Comment by Jairo-Martinez** [comment]
Hi @Alexey-T 
I am using

    [sidebar1]
    hint=Terminal
    icon={dir}/terminal.png
    method=open_on_start

But it is creating me something like this (two icons):

![screenshot_05](https://user-images.githubusercontent.com/5806694/81669477-e70a8980-940b-11ea-88e9-58732fc87049.png)

I know that the snippets panel is a Side Bar but the Terminal is a bottom panel, it is the expected behavior?

**Comment by Alexey-T** [comment]
yes, expected one. we don't have yet API to place inital btn for bottom panel. so my suggestion is not ok
